import type { Metadata } from 'next'
import { Sora, Space_Grotesk, Work_Sans } from 'next/font/google'
import { Navbar } from '@/components/Navbar'
import { PageTransition } from '@/components/PageTransition'
import './globals.css'

const bodyText = Work_Sans({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const titleText = Sora({
  variable: '--font-sora',
  subsets: ['latin']
})

const customFont = Space_Grotesk({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-custom',
  style: 'normal',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body
        className={`${bodyText.variable} ${titleText.variable} ${customFont.variable} bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px] antialiased dark:bg-slate-950 dark:[&>div]:bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)]`}
      >
        <Navbar />
        {/* Main content area with page transition */}
        <main className="relative z-10 mx-auto max-w-4xl border-x border-slate-200 transition-colors md:px-6 lg:px-8 dark:border-slate-800">
          <PageTransition>{children}</PageTransition>
        </main>
      </body>
    </html>
  )
}
