import type { Metadata } from 'next'
import { Sora, Space_Grotesk, Work_Sans } from 'next/font/google'
import { Navbar } from '@/components/Navbar'
import { ThemeProvider } from '@/components/ThemeProvider'
import { PageTransition } from '@/components/PageTransition'
import './globals.css'

const bodyText = Work_Sans({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const titleText = Sora({
  variable: '--font-sora',
  subsets: ['latin']
})

const customFont = Space_Grotesk({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-custom',
  style: 'normal',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bodyText.variable} ${titleText.variable} ${customFont.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="relative z-10 mx-auto max-w-4xl rounded-lg bg-white px-4 py-8 shadow-lg md:px-6 lg:px-8 dark:bg-gray-900">
            <PageTransition>{children}</PageTransition>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
